version: "3.9"

networks:
  auth-network:
    driver: auth-driver-1

volumes:
  auth_database_vol:
  cars_database_vol:
  insurance_database_vol:
  notification_database_vol:
  spendings_database_vol:

services:
  event_redis:
    image: redis
    restart: always
    ports:
      - 7001:6379

  auth_database:
    image: mongo
    restart: always
    ports:
      - 8000:27017
    volumes:
      - auth_database_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  auth:
    build: ./auth-service
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_HOST: auth_database
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      EVENT_REDIS_HOST: event_redis
      NOTIFICATION_SERVICE_HOST: notification:3003

  cars_database:
    image: mongo
    restart: always
    ports:
      - 8001:27017
    volumes:
      - cars_database_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  cars_redis:
    image: redis
    restart: always
    ports:
      - 7000:6379
  cars:
    build: ./cars-service
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      DATABASE_HOST: cars_database
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      CACHE_REDIS_HOST: cars_redis
      EVENT_REDIS_HOST: event_redis

  notification_database:
    image: mongo
    restart: always
    ports:
      - 8002:27017
    volumes:
      - notification_database_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  notification:
    build: ./notification-service
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: development
      DATABASE_HOST: notification_database
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      EVENT_REDIS_HOST: event_redis

  insurance_database:
    image: mongo
    restart: always
    ports:
      - 8003:27017
    volumes:
      - insurance_database_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  insurance:
    build: ./insurance-service
    ports:
      - "3004:3004"
    environment:
      NODE_ENV: development
      DATABASE_HOST: insurance_database
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password

  spendings_database:
    image: mongo
    restart: always
    ports:
      - 8004:27017
    volumes:
      - spendings_database_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  spendings:
    build: ./spendings-service
    ports:
      - "3005:3005"
    environment:
      NODE_ENV: development
      DATABASE_HOST: spednings_database
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
