version: "3.9"

volumes:
  auth_database_container:

services:
  auth_database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - auth_database_container:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
